const RestrictedWords = [
    // Banned: Gore Words
    'Blood',
    'Bloodbath',
    'Crucifixion',
    'Bloody',
    'Flesh',
    'Bruises',
    'Car crash',
    'Corpse',
    'Crucified',
    'Cutting',
    'Decapitate',
    'Infested',
    'Gruesome',
    'Kill',
    'Infected',
    'Sadist',
    'Slaughter',
    'Teratoma',
    'Tryphophobia',
    'Wound',
    'Cronenberg',
    'Khorne',
    'Cannibal',
    'Cannibalism',
    'Visceral',
    'Guts',
    'Bloodshot',
    'Gory',
    'Killing',
    'Surgery',
    'Vivisection',
    'Massacre',
    'Hemoglobin',
    'Suicide',
    'Female Body Parts',

    // Banned: Adult Words
    'ahegao',
    'pinup',
    'ballgag',
    'Playboy',
    'Bimbo',
    'pleasure',
    'bodily fluids',
    'pleasures',
    'boudoir',
    'rule34',
    'brothel',
    'seducing',
    'dominatrix',
    'seductive',
    'erotic seductive',
    'fuck',
    'sensual',
    'Hardcore',
    'sexy',
    'Hentai',
    'Shag',
    'horny',
    'shibari',
    'incest',
    'Smut',
    'jav',
    'succubus',
    'Jerk off king at pic',
    'thot',
    'kinbaku',
    'transparent',
    'legs spread',
    'twerk',
    'making love',
    'voluptuous',
    'naughty',
    'wincest',
    'orgy',
    'Sultry',
    'XXX',
    'Bondage',
    'Bdsm',
    'Dog collar',
    'Slavegirl',
    'Transparent and Translucent',

    // Banned: Body Parts Words
    'Arse',
    'Labia',
    'Ass',
    'Mammaries',
    'Human centipede',
    'Badonkers',
    'Minge',
    'Massive chests',
    'Big Ass',
    'Mommy',
    'Booba',
    'Nipple',
    'Booty',
    'Oppai',
    'Bosom',
    'Organs',
    'Breasts',
    'Ovaries',
    'Busty',
    'Penis',
    'Clunge',
    'Phallus',
    'Crotch',
    'sexy female',
    'Dick',
    'Skimpy',
    'Girth',
    'Thick',
    'Honkers',
    'Vagina',
    'Hooters',
    'Veiny',
    'Knob',


    // Banned: Clothing Words
    'no clothes',
    'Speedo',
    'au naturale',
    'no shirt',
    'bare chest',
    'nude',
    'barely dressed',
    'bra',
    'risqué',
    'clear',
    'scantily',
    'clad',
    'cleavage',
    'stripped',
    'full frontal unclothed',
    'invisible clothes',
    'wearing nothing',
    'lingerie with no shirt',
    'naked',
    'without clothes on',
    'negligee',
    'zero clothes',

    // Banned: Taboo Words
    'Taboo',
    'Fascist',
    'Nazi',
    'Prophet Mohammed',
    'Slave',
    'Coon',
    'Honkey',
    'Arrested',
    'Jail',
    'Handcuffs',


    // Banned: Drugs Words
    'Drugs',
    'Cocaine',
    'Heroin',
    'Meth',
    'Crack',
    'Torture',
    'Disturbing',
    'Farts', , 'Fart',
    'Poop',
    'Warts',
    'Xi Jinping',
    'Shit',
    'Pleasure',
    'Errect',
    'Big Black',
    'Brown pudding',
    'Bunghole',
    'Vomit',
    'Voluptuous',
    'Seductive',
    'Sperm',
    'Hot',
    'Sexy',
    'Sensored',
    'Censored',
    'Silenced',
    'Deepfake',
    'Inappropriate',
    'Pus',
    'Waifu',
    'mp5',
    'Succubus',
    '1488',
    'Surgery',

];

export default RestrictedWords;
